FROM node:20

LABEL version="1.0"
LABEL description="Client Docker Image - React"
LABEL maintainer = ["kamuchan@ncsu.edu"]

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]