version: '3.8'

services:

  client:
    image: ncsu-cure/client
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - server

  server:
    image: ncsu-cure/server
    ports:
      - 8080:8080 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 40s
